# Makefile for source/Simulation/SimulationMain/StreamingSineWave

Simulation += Simulation_data.o

Simulation_init.o : Simulation_data.o ProgramHeaderModule.o RadiationFieldsModule.o ThornadoInitializationModule.o
Simulation_initBlock.o : Simulation_data.o ProgramHeaderModule.o RadiationFieldsModule.o UnitsModule.o

