Eos += eos_gphData.o                    	 \
           eos_gphFindTablePos.o                 \
           eos_gphGetAnyTableData.o       \
           eos_gphGetTabulatedData.o      \
           eos_gphInterface.o                    \
           eos_gphGpN.o                      \
           eos_gphLogOutsideCounts.o             \
           eos_gphReadGpNTables.o            \
           eos_gphUpdateOutsideCount.o           \
           eos_gphZeroOutsideCounts.o

#           eos_gphBrowseIonmixTables.o           \
           eos_gphBrowseIonmix4Tables.o          \
           eos_gphBrowseTables.o                 \
           eos_gphReadIonmixTables.o             \
           eos_gphReadTables.o                   \

