Eos += eos_gphData.o                    	 \
           eos_gphBrowseIonmixTables.o           \
           eos_gphBrowseIonmix4Tables.o          \
           eos_gphBrowseTables.o                 \
           eos_gphFindTablePos.o                 \
           eos_gphGetSpeciesAnyTableData.o       \
           eos_gphGetSpeciesTabulatedData.o      \
           eos_gphInterface.o                    \
           eos_gphIonmix4.o                      \
           eos_gphLogOutsideCounts.o             \
           eos_gphReadIonmixTables.o             \
           eos_gphReadIonmix4Tables.o            \
           eos_gphReadTables.o                   \
           eos_gphUpdateOutsideCount.o           \
           eos_gphZeroOutsideCounts.o
